package com.kat.bookstore.service;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.kat.bookstore.domain.*;

public class ClientBaseMgr {
	
	private Connection connect;
	private Statement statement;
	private String url = "jdbc:hsqldb:hsql://localhost/workdb";

	private String createTableClient = "CREATE TABLE Client(id bigint GENERATED BY DEFAULT AS IDENTITY(start with 1) PRIMARY KEY," +
										"name varchar(20), surname varchar(20))";
	private PreparedStatement addClientStmt;
	private PreparedStatement deleteAllClientsStmt;
	private PreparedStatement getAllClientsStmt;
	private PreparedStatement getAllClientsIDstmt;
	private PreparedStatement getClientStmt;
	private PreparedStatement deleteClientListStmt;
	private PreparedStatement findClientByNameStmt;
	private PreparedStatement findClientBySurnameStmt;
	List<Integer> listID = new ArrayList<Integer>();
	
	public ClientBaseMgr() {
	try {
		connect = DriverManager.getConnection(url);
		statement = connect.createStatement();

		ResultSet rs = connect.getMetaData().getTables(null, null, null, null);
		boolean tableExists = false;
		
		while (rs.next()) {
			if ("Client".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
				tableExists = true;
				break;
			} 
		}
	

		if (!tableExists) statement.executeUpdate(createTableClient);

		addClientStmt = connect.prepareStatement("INSERT INTO Client (name, surname) VALUES (?, ?)");
		deleteClientListStmt = connect.prepareStatement("DELETE FROM Client WHERE id = ?");
		deleteAllClientsStmt = connect.prepareStatement("DELETE FROM Client");
		getClientStmt = connect.prepareStatement("SELECT * FROM Client WHERE id = ?");
		getAllClientsStmt = connect.prepareStatement("SELECT * FROM Client");
		findClientByNameStmt = connect.prepareStatement("SELECT id FROM Client WHERE name = ?");
		findClientBySurnameStmt = connect.prepareStatement("SELECT id FROM Client WHERE surname = ?");
		getAllClientsIDstmt = connect.prepareStatement("SELECT id FROM Client");
		
		} catch (SQLException e) {
		e.printStackTrace();
		}
	}


	Connection getConnection() {
		return connect;
	}

	public int addClient(Client c) {
		int count = 0;
		try {
			addClientStmt.setString(1, c.getName());
			addClientStmt.setString(2, c.getSurname());

			count = addClientStmt.executeUpdate();

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return count;
	}
	
	public void getClient() {
		
		try {
			ResultSet rs = getClientStmt.executeQuery();
			
			Client c = new Client();
			c.setId(rs.getInt("id"));
			c.setName(rs.getString("name"));
			c.setSurname(rs.getString("surname"));
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
	};

	public List<Integer> getAllClientsID() {
		List<Integer> clientList = new ArrayList<Integer>();
		try {
			ResultSet rs = getAllClientsIDstmt.executeQuery();
			while (rs.next())
				clientList.add(rs.getInt("id"));
		} catch (SQLException e) {
			e.printStackTrace();
		}

		return clientList;
	}
	
	public List<Client> getAllClients() {
		List<Client> clients = new ArrayList<Client>();

		try {
			ResultSet rs = getAllClientsStmt.executeQuery();

			while (rs.next()) {
				Client c = new Client();
				c.setId(rs.getInt("id"));
				c.setName(rs.getString("name"));
				c.setSurname(rs.getString("surname"));
				clients.add(c);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return clients;
	}
	
	
	public void deleteClientsList(List<Integer> list) {
		try {
			for (Integer id : list) {
				deleteClientListStmt.setInt(1, id);
				deleteClientListStmt.executeUpdate();
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	} 
	
	public void deleteAllClients() {
		try {
			deleteAllClientsStmt.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public List<Integer> findClientByName(String name) {
		try {
			List<Integer> result = new ArrayList<Integer>();
			findClientByNameStmt.setString(1, name);
			ResultSet rs = findClientByNameStmt.executeQuery();
			while (rs.next())
				result.add(rs.getInt("ID"));
			return result;
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;
	}

	public List<Integer> findClientBySurname(String surname) {
		try {
			List<Integer> result = new ArrayList<Integer>();
			findClientBySurnameStmt.setString(1, surname);
			ResultSet rs = findClientBySurnameStmt.executeQuery();
			while (rs.next())
				result.add(rs.getInt("ID"));
			return result;
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;
	}

	
/*
	// klasa anonimowa
	public void printCustomerWithCondition(List<Customer> CustomerList,
			Condition condition) {
		for (Customer customer : CustomerList) {
			if (condition.getCondition(customer)) {
				System.out.println("Name: " + customer.getName()
						+ "\tSurname: " + customer.getSurname());
			}
		}
	}
	*/
}

